"""Custom fields on standard ERPNext DocTypes.

Implements Section 8 of the Technical Development Specification v1.0.
Applied through frappe.custom.doctype.custom_field.custom_field
.create_custom_fields, which is idempotent: if a fieldname already exists it
is updated in place, never duplicated, and installation never fails on an
existing field (Section 17.1).
"""

SERVICE_TYPE_OPTIONS = "\n".join([
    "",
    "Design Only",
    "Design + Supervision",
    "Supervision Only",
    "Design + Supervision + Execution",
    "Project Management + Supervision + Execution",
])

PROJECT_STAGE_OPTIONS = "\n".join([
    "",
    "Customer Intake", "Proposal / Contract", "Design", "Technical Review",
    "Licensing", "Tendering", "Execution", "Supervision", "Handover",
    "Closure", "Post-Completion", "Closed", "On Hold", "Cancelled",
])

CUSTOM_FIELDS = {
    "Lead": [
        dict(fieldname="custom_engineering_section", fieldtype="Section Break",
             label="Engineering Enquiry", insert_after="notes_tab", collapsible=1),
        dict(fieldname="custom_project_type", fieldtype="Data",
             label="Project Type / Category", insert_after="custom_engineering_section"),
        dict(fieldname="custom_project_location", fieldtype="Data",
             label="Project Location", insert_after="custom_project_type"),
        dict(fieldname="custom_estimated_budget", fieldtype="Currency",
             label="Estimated Budget", insert_after="custom_project_location"),
        dict(fieldname="custom_required_services", fieldtype="Small Text",
             label="Required Services", insert_after="custom_estimated_budget"),
        dict(fieldname="custom_project_brief", fieldtype="Link",
             label="Project Brief", options="Project Brief",
             insert_after="custom_required_services"),
    ],
    "Opportunity": [
        dict(fieldname="custom_engineering_section", fieldtype="Section Break",
             label="Engineering", insert_after="opportunity_type", collapsible=0),
        dict(fieldname="custom_project_brief", fieldtype="Link",
             label="Project Brief", options="Project Brief",
             insert_after="custom_engineering_section"),
        dict(fieldname="custom_service_type", fieldtype="Select",
             label="Service Type", options=SERVICE_TYPE_OPTIONS,
             insert_after="custom_project_brief", reqd=1),
    ],
    "Quotation": [
        dict(fieldname="custom_engineering_section", fieldtype="Section Break",
             label="Engineering Proposal", insert_after="order_type", collapsible=0),
        dict(fieldname="custom_project_brief", fieldtype="Link",
             label="Project Brief", options="Project Brief",
             insert_after="custom_engineering_section"),
        dict(fieldname="custom_service_type", fieldtype="Select",
             label="Service Type", options=SERVICE_TYPE_OPTIONS,
             insert_after="custom_project_brief", reqd=1),
        dict(fieldname="custom_proposal_version", fieldtype="Data",
             label="Proposal Version", insert_after="custom_service_type"),
    ],
    "Project": [
        dict(fieldname="custom_engineering_tab", fieldtype="Tab Break",
             label="Engineering Control", insert_after="cost_center"),
        dict(fieldname="custom_scope_section", fieldtype="Section Break",
             label="Scope & Contract", insert_after="custom_engineering_tab"),
        dict(fieldname="custom_project_brief", fieldtype="Link",
             label="Project Brief", options="Project Brief",
             insert_after="custom_scope_section"),
        dict(fieldname="custom_service_type", fieldtype="Select",
             label="Service Type", options=SERVICE_TYPE_OPTIONS,
             insert_after="custom_project_brief"),
        dict(fieldname="custom_project_stage", fieldtype="Select",
             label="Project Stage", options=PROJECT_STAGE_OPTIONS,
             insert_after="custom_service_type",
             description="Controlled summary field updated through approved "
                         "process events (Section 9.1)."),
        dict(fieldname="custom_design_origin", fieldtype="Select",
             label="Design Origin", options="\nInternal\nExternal",
             insert_after="custom_project_stage"),
        dict(fieldname="custom_scope_cb", fieldtype="Column Break",
             insert_after="custom_design_origin"),
        dict(fieldname="custom_project_location", fieldtype="Data",
             label="Project Location", insert_after="custom_scope_cb"),
        dict(fieldname="custom_contract_no", fieldtype="Data",
             label="Client Contract No.", insert_after="custom_project_location"),
        dict(fieldname="custom_contract_date", fieldtype="Date",
             label="Contract Date", insert_after="custom_contract_no"),
        dict(fieldname="custom_contract_value", fieldtype="Currency",
             label="Contract Value", insert_after="custom_contract_date",
             description="Commercial reference only; no GL impact."),
        dict(fieldname="custom_team_section", fieldtype="Section Break",
             label="Responsibility", insert_after="custom_contract_value"),
        dict(fieldname="custom_project_manager", fieldtype="Link",
             label="Project Manager", options="User",
             insert_after="custom_team_section"),
        dict(fieldname="custom_design_lead", fieldtype="Link",
             label="Design Lead", options="User",
             insert_after="custom_project_manager"),
        dict(fieldname="custom_technical_manager", fieldtype="Link",
             label="Technical Manager", options="User",
             insert_after="custom_design_lead"),
        dict(fieldname="custom_team_cb", fieldtype="Column Break",
             insert_after="custom_technical_manager"),
        dict(fieldname="custom_supervision_manager", fieldtype="Link",
             label="Supervision Manager", options="User",
             insert_after="custom_team_cb"),
        dict(fieldname="custom_primary_contractor", fieldtype="Link",
             label="Primary Contractor", options="Supplier",
             insert_after="custom_supervision_manager"),
        dict(fieldname="custom_status_section", fieldtype="Section Break",
             label="Stage Status Summary", insert_after="custom_primary_contractor"),
        dict(fieldname="custom_license_status", fieldtype="Data",
             label="License Status", read_only=1,
             insert_after="custom_status_section"),
        dict(fieldname="custom_tender_status", fieldtype="Data",
             label="Tender Status", read_only=1,
             insert_after="custom_license_status"),
        dict(fieldname="custom_closure_status", fieldtype="Select",
             label="Closure Status", options="\nOpen\nIn Closure\nClosed",
             insert_after="custom_tender_status"),
        dict(fieldname="custom_kpi_cb", fieldtype="Column Break",
             insert_after="custom_closure_status"),
        dict(fieldname="custom_document_completion_pct", fieldtype="Percent",
             label="Document Completion %", read_only=1,
             insert_after="custom_kpi_cb"),
        dict(fieldname="custom_engineering_progress_pct", fieldtype="Percent",
             label="Engineering Progress %", read_only=1,
             insert_after="custom_document_completion_pct"),
        dict(fieldname="custom_site_progress_pct", fieldtype="Percent",
             label="Site Progress %", read_only=1,
             insert_after="custom_engineering_progress_pct"),
    ],
    "Task": [
        dict(fieldname="custom_engineering_section", fieldtype="Section Break",
             label="Engineering", insert_after="progress", collapsible=1),
        dict(fieldname="custom_engineering_stage", fieldtype="Select",
             label="Engineering Stage",
             options="\nDesign\nTechnical\nTender\nSite\nClosure",
             insert_after="custom_engineering_section"),
        dict(fieldname="custom_discipline", fieldtype="Select",
             label="Discipline",
             options="\nArchitectural\nStructural\nMechanical\nElectrical"
                     "\nPlumbing / Sanitary\nCivil\nLandscape\nInterior"
                     "\nFire & Life Safety\nGeneral / Coordination\nOther",
             insert_after="custom_engineering_stage"),
        dict(fieldname="custom_deliverable_required", fieldtype="Check",
             label="Deliverable Required", insert_after="custom_discipline"),
        dict(fieldname="custom_approval_required", fieldtype="Check",
             label="Approval Required", insert_after="custom_deliverable_required"),
    ],
    "Supplier": [
        dict(fieldname="custom_contractor_section", fieldtype="Section Break",
             label="Contractor Classification", insert_after="supplier_group",
             collapsible=1),
        dict(fieldname="custom_supplier_type", fieldtype="Select",
             label="Supplier Type",
             options="\nContractor\nSubcontractor\nMEP\nSupplier\nConsultant",
             insert_after="custom_contractor_section"),
        dict(fieldname="custom_contractor_specialty", fieldtype="Small Text",
             label="Contractor Specialty", insert_after="custom_supplier_type"),
        dict(fieldname="custom_prequalification_status", fieldtype="Select",
             label="Prequalification Status",
             options="\nApproved\nConditional\nRejected\nExpired",
             insert_after="custom_contractor_specialty"),
        dict(fieldname="custom_prequalification_expiry", fieldtype="Date",
             label="Prequalification Expiry",
             insert_after="custom_prequalification_status"),
    ],
    "Request for Quotation": [
        dict(fieldname="custom_project", fieldtype="Link", label="Project",
             options="Project", insert_after="company"),
        dict(fieldname="custom_tender_package", fieldtype="Link",
             label="Tender Package", options="Tender Package",
             insert_after="custom_project"),
        dict(fieldname="custom_tender_round", fieldtype="Int",
             label="Tender Round", insert_after="custom_tender_package"),
    ],
    "Supplier Quotation": [
        dict(fieldname="custom_project", fieldtype="Link", label="Project",
             options="Project", insert_after="company"),
        dict(fieldname="custom_tender_package", fieldtype="Link",
             label="Tender Package", options="Tender Package",
             insert_after="custom_project"),
    ],
    "Purchase Order": [
        dict(fieldname="custom_tender_package", fieldtype="Link",
             label="Tender Package", options="Tender Package",
             insert_after="project"),
        dict(fieldname="custom_contract_type", fieldtype="Select",
             label="Contract Type",
             options="\nMain Contract\nSubcontract\nMaterial\nService",
             insert_after="custom_tender_package"),
    ],
    "Purchase Invoice": [
        dict(fieldname="custom_progress_certificate", fieldtype="Link",
             label="Progress Certificate",
             options="Contractor Progress Certificate",
             insert_after="project"),
    ],
    "Issue": [
        dict(fieldname="custom_warranty_section", fieldtype="Section Break",
             label="Project / Warranty", insert_after="customer", collapsible=0),
        dict(fieldname="custom_project", fieldtype="Link", label="Project",
             options="Project", insert_after="custom_warranty_section"),
        dict(fieldname="custom_issue_category", fieldtype="Select",
             label="Issue Category",
             options="\nDefect\nWarranty\nMaintenance\nTechnical",
             insert_after="custom_project"),
        dict(fieldname="custom_responsible_supplier", fieldtype="Link",
             label="Responsible Contractor/Supplier", options="Supplier",
             insert_after="custom_issue_category"),
        dict(fieldname="custom_warranty_due_date", fieldtype="Date",
             label="Warranty Due Date", insert_after="custom_responsible_supplier"),
        dict(fieldname="custom_severity", fieldtype="Select",
             label="Severity", options="\nLow\nMedium\nHigh\nCritical",
             insert_after="custom_warranty_due_date"),
        dict(fieldname="custom_resolution_verified_by", fieldtype="Link",
             label="Resolution Verified By", options="User",
             insert_after="custom_severity",
             description="Required to close a Warranty/Defect issue (BR-016)."),
    ],
}


def get_custom_fields():
    return CUSTOM_FIELDS
